version: '3'
services:
  test1:
    build: ./test1
    image: test1
    container_name: test1
    privileged: true
    networks:
#      - test-network
      app_net:
        ipv4_address: 172.30.0.10
    command: /sbin/init

  test2:
    build: ./test2
    image: test2
    container_name: test2
    privileged: true
    networks:
#      - test-network
      app_net:
        ipv4_address: 172.30.0.20
    command: /sbin/init

networks:
#    test-network:
    app_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.30.0.0/24

#      external: true
