filebeat:
  prospectors:
    - paths:
        - /var/log/nginx/access.log
      input_type: log
    - paths:
        - /var/log/nginx/sar*
      input_type: log

output:
  logstash:
    hosts: ["logstash:5044"]
