version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch
    container_name: elasticsearch
    privileged: true
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - node.master=true
      - node.data=true
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
#      - test-network
      private_net:
        ipv4_address: 192.168.100.10 
    command: /sbin/init

  kibana:
    build: ./kibana
    image: kibana
    container_name: kibana
    privileged: true
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
#      - test-network
      private_net:
        ipv4_address: 192.168.100.20 
    command: /sbin/init

networks:
#    test-network:
    private_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.100.0/24

#      external: true
