- pipeline.id: logstash
  pipeline.batch.size: 125
#  path.config: "/etc/logstash/conf.d/logstash.cfg"
  /usr/share/logstash/pipeline/logstash.conf
  pipeline.workers: 1
- pipeline.id: sar
  pipeline.batch.size: 125
#  path.config: "/etc/logstash/conf.d/sar.cfg"
  /usr/share/logstash/pipeline/sar.conf
  pipeline.workers: 1
