version: "3"
services:
  logstash:
    build: ./filebeat
    image: filebeat
    container_name: filebeat
    privileged: true
    environment:
      discovery.type: single-node
    networks:
      private_net:
        ipv4_address:192.168.200.10
    ports:
      - "9200:9200"
    volumes:
      - ./pipeline:/usr/share/logstash/pipelin
    depends_on: logstash
    command: /sbin/init
    
  
  logstash:
    build: ./logstash
    image: logstash
    container_name: logstash
    privileged: true
    environment:
      discovery.type: single-node
    networks:
      private_net:
        ipv4_address:192.168.200.20
    ports:
      - "9200:9200"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./log:/var/log
    depends_on:
      - elasticsearch
    command: /sbin/init

    
  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch
    container_name: elasticsearch
    privileged: true
    environment:
      discovery.type: single-node
    networks:
      private_net:
        ipv4_address:192.168.200.30
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    command: /sbin/init


  kibana:
    build: ./kibana
    image: kibana
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      private_net:
        ipv4_address:192.168.200.40
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    command: /sbin/init

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    networks:
      private_net:
        ipv4_address:192.168.200.50
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/log:/var/log/nginx
      - ./data/nginx/html:/usr/share/nginx/html

networks:
  private_net:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 192.168.200.0/24

