version: '2'
services:
  elasticsearch:
    mem_limit: 1024m
    build: ./es_d
    container_name: es_c_el
    image: es_i_el:1.0.5
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    mem_limit: 512m
    build: ./kibana_d
    container_name: kibana_c_el
    image: kibana_i_el:1.0.4
    ports:
      - 5601:5601


  logstash:
    mem_limit: 512m
    build: ./logstash_d
    container_name: logstash_c_el
    image: logstash_i_el:1.0.21
    ports:
      - 5044:5044

  beats:
    mem_limit: 512m
    build: ./beats_d
    container_name: beats_c_el
    image: beats_i_el:1.0.1
    volumes:
      - ./data/nginx:/var/log/nginx/

  web:
    mem_limit: 512m
    image: nginx:1.10
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/var/log/nginx

