version: '2'

services:

  server1:
    image: centos:7
    container_name: 'controller'
    restart: always
    ports:
      - '2210:22'
    networks:
      app_net:
        ipv4_address: 172.17.0.10

  server2:
    image: centos:7
    container_name: 'target'
    restart: always
    ports:
      - '2210:22'
    networks:
      app_net:
        ipv4_address: 172.17.0.20


networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.17.0.0/16
         gateway: 172.18.0.1
