version: '3'
services:
  controller:
    build: ./controller
    image: controller
    container_name: controller
    privileged: true
    networks:
#      - test-network
      private_net:
        ipv4_address: 192.168.100.10 
    command: /sbin/init

  target:
    build: ./target
    image: target
    container_name: target
    privileged: true
    networks:
#      - test-network
      private_net:
        ipv4_address: 192.168.100.20 
    command: /sbin/init

networks:
#    test-network:
    private_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.100.0/24

#      external: true
