version: '3.3'

services:

  server1:
    image: centos:7
    container-name: 'controller'
    restart: always
    ports:
      - 2210:22
    networks:
      app_net:
        ipv4_address: 192.168.100.10

  server2:
    image: centos:7
    container-name: 'target'
    restart: always
    ports:
      - 2210:22
    networks:
      app_net:
        ipv4_address: 192.168.100.20


networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.0.0/24
#         gateway: 172.30.0.1
