version: '2'

services:

  server1:
    image: centos:7
    container_name: 'controller'
    restart: always
    tty: true
#    ports:
#      - '12210:22'
    networks:
      app_net:
        ipv4_address: 173.17.0.10

  server2:
    image: centos:7
    container_name: 'target'
    restart: always
    tty: true
#    ports:
#      - '12210:22'
    networks:
      app_net:
        ipv4_address: 173.17.0.20


networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 173.17.0.0/16
         gateway: 173.17.0.1
